# Generated by Django 2.2.5 on 2019-10-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('citta', models.CharField(max_length=200)),
                ('telefono_fisso', models.CharField(max_length=10)),
                ('telefono_cellulare', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=100)),
                ('scadenza', models.DateField(null=True)),
                ('inizio_incarico', models.DateField(null=True)),
                ('fine_incarico', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_contratto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FasciaPrezzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fascia_min', models.IntegerField(null=True)),
                ('fascia_max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mutuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutuo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_ruolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_sesso', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaImmobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipologia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Ruolo')),
            ],
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('indirizzo', models.CharField(max_length=100)),
                ('stato', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=5000)),
                ('immobili_proposti', models.CharField(max_length=5000)),
                ('prezzo', models.IntegerField()),
                ('tipologia', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=5000, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
                ('contratto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Contratto')),
                ('fascia_prezzo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.FasciaPrezzo')),
                ('mutuo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Mutuo')),
            ],
        ),
    ]
